repos:
  - repo: local
    hooks:
      - id: bandit-all
        name: bandit security scan
        entry: python scripts/pre_commit_all.py bandit --skip B101
        language: python
        additional_dependencies:
          - bandit==1.9.4
        always_run: true
        pass_filenames: false
        verbose: true
        log_file: pre-commit.log