name: Tests

on:
  push:
  pull_request:

jobs:
  lint-static-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: bigfive-ci
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict
          miniforge-version: latest
          python-version: "3.10"

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install --yes \
            numpy pandas matplotlib plotly seaborn scipy scikit-learn==1.5.2 \
            joblib pytest factor-analyzer==0.5.1 r-base r-psych rpy2 \
            ruff pre-commit

      - name: Run tests
        shell: bash -el {0}
        run: pytest

      - name: Run Ruff
        shell: bash -el {0}
        run: ruff check .

      - name: Run pre-commit
        shell: bash -el {0}
        run: pre-commit run --all-files


  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: bigfive-ci
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install --yes \
            numpy pandas matplotlib plotly seaborn scipy scikit-learn==1.5.2 \
            joblib pytest factor-analyzer==0.5.1 r-base r-psych rpy2 \

      - name: Run tests
        shell: bash -el {0}
        run: pytest


  build:
    runs-on: ubuntu-latest

    needs:
      - lint-static-checks
      - tests

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: bigfive-ci
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict
          miniforge-version: latest
          python-version: "3.10"

      - name: Install build dependencies
        shell: bash -el {0}
        run: |
          conda install --yes \
            numpy pandas matplotlib plotly seaborn scipy scikit-learn==1.5.2 \
            joblib pytest factor-analyzer==0.5.1 r-base r-psych rpy2 
            
          python -m pip install build

      - name: Build package
        shell: bash -el {0}
        run: python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bigfive-package-${{ github.sha }}
          path: dist/